#!/bin/bash

if [ ! -d /data/exports ]; then
  mkdir -p /data/exports
fi

if [ `stat -c "%a" /data` != "777" ] ; then
  chmod 777 /data
fi

if [ `stat -c "%G:%U" /data/exports` != 'root:root' ] ; then
  chown -R root:root /data/exports
fi
